/**
 * IANA Timezone definitions.
 *
 * Generated from cards.arda.common.lib.domain.general.time.IanaInfo (Kotlin).
 * 596 timezone entries covering all IANA zones.
 */

/** Information about an IANA timezone. */
export interface IanaTimezoneInfo {
  /** IANA timezone name (e.g. "America/New_York"). */
  tzName: string;
  /** Standard UTC offset (e.g. "-05:00"). */
  utcOffsetStd: string;
  /** Daylight saving UTC offset (empty if no DST). */
  utcOffsetDst: string;
  /** Standard time abbreviation (e.g. "EST"). */
  abbreviationStd: string;
  /** Daylight saving time abbreviation (empty if no DST). */
  abbreviationDst: string;
}

/** All IANA timezones with offset and abbreviation metadata. */
export const IANA_TIMEZONES: readonly IanaTimezoneInfo[] = [
  {
    tzName: 'Africa/Abidjan',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Accra',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Addis_Ababa',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Algiers',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'CET',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Asmara',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Asmera',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Bamako',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Bangui',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Banjul',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Bissau',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Blantyre',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Brazzaville',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Bujumbura',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Cairo',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Africa/Casablanca',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+00:00',
    abbreviationStd: '+01',
    abbreviationDst: '+00',
  },
  {
    tzName: 'Africa/Ceuta',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Africa/Conakry',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Dakar',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Dar_es_Salaam',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Djibouti',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Douala',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/El_Aaiun',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+00:00',
    abbreviationStd: '+01',
    abbreviationDst: '+00',
  },
  {
    tzName: 'Africa/Freetown',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Gaborone',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Harare',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Johannesburg',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'SAST',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Juba',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Kampala',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Khartoum',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Kigali',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Kinshasa',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Lagos',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Libreville',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Lome',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Luanda',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Lubumbashi',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Lusaka',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Malabo',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Maputo',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Maseru',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'SAST',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Mbabane',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'SAST',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Mogadishu',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Monrovia',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Nairobi',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Ndjamena',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Niamey',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Nouakchott',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Ouagadougou',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Porto-Novo',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'WAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Sao_Tome',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Timbuktu',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Tripoli',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'EET',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Tunis',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: 'CET',
    abbreviationDst: '',
  },
  {
    tzName: 'Africa/Windhoek',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'CAT',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Adak',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '-09:00',
    abbreviationStd: 'HST',
    abbreviationDst: 'HDT',
  },
  {
    tzName: 'America/Anchorage',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'America/Anguilla',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Antigua',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Araguaina',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Buenos_Aires',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Catamarca',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/ComodRivadavia',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Cordoba',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Jujuy',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/La_Rioja',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Mendoza',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Rio_Gallegos',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Salta',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/San_Juan',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/San_Luis',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Tucuman',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Argentina/Ushuaia',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Aruba',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Asuncion',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: '-04',
    abbreviationDst: '-03',
  },
  {
    tzName: 'America/Atikokan',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Atka',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '-09:00',
    abbreviationStd: 'HST',
    abbreviationDst: 'HDT',
  },
  {
    tzName: 'America/Bahia',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Bahia_Banderas',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Barbados',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Belem',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Belize',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Blanc-Sablon',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Boa_Vista',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Bogota',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Boise',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Buenos_Aires',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Cambridge_Bay',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Campo_Grande',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Cancun',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Caracas',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Catamarca',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Cayenne',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Cayman',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Chicago',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Chihuahua',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Ciudad_Juarez',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Coral_Harbour',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Cordoba',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Costa_Rica',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Creston',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Cuiaba',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Curacao',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Danmarkshavn',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Dawson',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Dawson_Creek',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Denver',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Detroit',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Dominica',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Edmonton',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Eirunepe',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'America/El_Salvador',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Ensenada',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'America/Fort_Nelson',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Fort_Wayne',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Fortaleza',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Glace_Bay',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'America/Godthab',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '-01:00',
    abbreviationStd: '-02',
    abbreviationDst: '-01',
  },
  {
    tzName: 'America/Goose_Bay',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'America/Grand_Turk',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Grenada',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Guadeloupe',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Guatemala',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Guayaquil',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Guyana',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Halifax',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'America/Havana',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Hermosillo',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Indiana/Indianapolis',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Indiana/Knox',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Indiana/Marengo',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Indiana/Petersburg',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Indiana/Tell_City',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Indiana/Vevay',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Indiana/Vincennes',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Indiana/Winamac',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Indianapolis',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Inuvik',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Iqaluit',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Jamaica',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Jujuy',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Juneau',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'America/Kentucky/Louisville',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Kentucky/Monticello',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Knox_IN',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Kralendijk',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/La_Paz',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Lima',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Los_Angeles',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'America/Louisville',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Lower_Princes',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Maceio',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Managua',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Manaus',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Marigot',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Martinique',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Matamoros',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Mazatlan',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Mendoza',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Menominee',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Merida',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Metlakatla',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'America/Mexico_City',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Miquelon',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '-02:00',
    abbreviationStd: '-03',
    abbreviationDst: '-02',
  },
  {
    tzName: 'America/Moncton',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'America/Monterrey',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Montevideo',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Montreal',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Montserrat',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Nassau',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/New_York',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Nipigon',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Nome',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'America/Noronha',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '',
    abbreviationStd: '-02',
    abbreviationDst: '',
  },
  {
    tzName: 'America/North_Dakota/Beulah',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/North_Dakota/Center',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/North_Dakota/New_Salem',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Nuuk',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '-01:00',
    abbreviationStd: '-02',
    abbreviationDst: '-01',
  },
  {
    tzName: 'America/Ojinaga',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Panama',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Pangnirtung',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Paramaribo',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Phoenix',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Port_of_Spain',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Port-au-Prince',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Porto_Acre',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Porto_Velho',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Puerto_Rico',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Punta_Arenas',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Rainy_River',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Rankin_Inlet',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Recife',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Regina',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Resolute',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Rio_Branco',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Rosario',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Santa_Isabel',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'America/Santarem',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Santiago',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: '-04',
    abbreviationDst: '-03',
  },
  {
    tzName: 'America/Santo_Domingo',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Sao_Paulo',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Scoresbysund',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '-01:00',
    abbreviationStd: '-02',
    abbreviationDst: '-01',
  },
  {
    tzName: 'America/Shiprock',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'America/Sitka',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'America/St_Barthelemy',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/St_Johns',
    utcOffsetStd: '-03:30',
    utcOffsetDst: '-02:30',
    abbreviationStd: 'NST',
    abbreviationDst: 'NDT',
  },
  {
    tzName: 'America/St_Kitts',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/St_Lucia',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/St_Thomas',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/St_Vincent',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Swift_Current',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Tegucigalpa',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Thule',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'America/Thunder_Bay',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Tijuana',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'America/Toronto',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'America/Tortola',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Vancouver',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'America/Virgin',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: 'AST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Whitehorse',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'America/Winnipeg',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'America/Yakutat',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'America/Yellowknife',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'Antarctica/Casey',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/Davis',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/DumontDUrville',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/Macquarie',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Antarctica/Mawson',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/McMurdo',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '+13:00',
    abbreviationStd: 'NZST',
    abbreviationDst: 'NZDT',
  },
  {
    tzName: 'Antarctica/Palmer',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/Rothera',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/South_Pole',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '+13:00',
    abbreviationStd: 'NZST',
    abbreviationDst: 'NZDT',
  },
  {
    tzName: 'Antarctica/Syowa',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Antarctica/Troll',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: '+00',
    abbreviationDst: '+02',
  },
  {
    tzName: 'Antarctica/Vostok',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Arctic/Longyearbyen',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Asia/Aden',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Almaty',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Amman',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Anadyr',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Aqtau',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Aqtobe',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Ashgabat',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Ashkhabad',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Atyrau',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Baghdad',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Bahrain',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Baku',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Bangkok',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Barnaul',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Beirut',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Asia/Bishkek',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Brunei',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Calcutta',
    utcOffsetStd: '+05:30',
    utcOffsetDst: '',
    abbreviationStd: 'IST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Chita',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: '+09',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Choibalsan',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Chongqing',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Chungking',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Colombo',
    utcOffsetStd: '+05:30',
    utcOffsetDst: '',
    abbreviationStd: '+0530',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Dacca',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Damascus',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Dhaka',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Dili',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: '+09',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Dubai',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Dushanbe',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Famagusta',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Asia/Gaza',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Asia/Harbin',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Hebron',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Asia/Ho_Chi_Minh',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Hong_Kong',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'HKT',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Hovd',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Irkutsk',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Istanbul',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Jakarta',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: 'WIB',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Jayapura',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: 'WIT',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Jerusalem',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'IST',
    abbreviationDst: 'IDT',
  },
  {
    tzName: 'Asia/Kabul',
    utcOffsetStd: '+04:30',
    utcOffsetDst: '',
    abbreviationStd: '+0430',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kamchatka',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Karachi',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: 'PKT',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kashgar',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kathmandu',
    utcOffsetStd: '+05:45',
    utcOffsetDst: '',
    abbreviationStd: '+0545',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Katmandu',
    utcOffsetStd: '+05:45',
    utcOffsetDst: '',
    abbreviationStd: '+0545',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Khandyga',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: '+09',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kolkata',
    utcOffsetStd: '+05:30',
    utcOffsetDst: '',
    abbreviationStd: 'IST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Krasnoyarsk',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kuala_Lumpur',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kuching',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Kuwait',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Macao',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Macau',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Magadan',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Makassar',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'WITA',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Manila',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'PST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Muscat',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Nicosia',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Asia/Novokuznetsk',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Novosibirsk',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Omsk',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Oral',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Phnom_Penh',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Pontianak',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: 'WIB',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Pyongyang',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: 'KST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Qatar',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Qostanay',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Qyzylorda',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Rangoon',
    utcOffsetStd: '+06:30',
    utcOffsetDst: '',
    abbreviationStd: '+0630',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Riyadh',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Saigon',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Sakhalin',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Samarkand',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Seoul',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: 'KST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Shanghai',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Singapore',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Srednekolymsk',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Taipei',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Tashkent',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Tbilisi',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Tehran',
    utcOffsetStd: '+03:30',
    utcOffsetDst: '',
    abbreviationStd: '+0330',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Tel_Aviv',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'IST',
    abbreviationDst: 'IDT',
  },
  {
    tzName: 'Asia/Thimbu',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Thimphu',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Tokyo',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: 'JST',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Tomsk',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Ujung_Pandang',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'WITA',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Ulaanbaatar',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Ulan_Bator',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Urumqi',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Ust-Nera',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Vientiane',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Vladivostok',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Yakutsk',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: '+09',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Yangon',
    utcOffsetStd: '+06:30',
    utcOffsetDst: '',
    abbreviationStd: '+0630',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Yekaterinburg',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Asia/Yerevan',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Atlantic/Azores',
    utcOffsetStd: '-01:00',
    utcOffsetDst: '+00:00',
    abbreviationStd: '-01',
    abbreviationDst: '+00',
  },
  {
    tzName: 'Atlantic/Bermuda',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'Atlantic/Canary',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'Atlantic/Cape_Verde',
    utcOffsetStd: '-01:00',
    utcOffsetDst: '',
    abbreviationStd: '-01',
    abbreviationDst: '',
  },
  {
    tzName: 'Atlantic/Faeroe',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'Atlantic/Faroe',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'Atlantic/Jan_Mayen',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Atlantic/Madeira',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'Atlantic/Reykjavik',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Atlantic/South_Georgia',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '',
    abbreviationStd: '-02',
    abbreviationDst: '',
  },
  {
    tzName: 'Atlantic/St_Helena',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Atlantic/Stanley',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/ACT',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/Adelaide',
    utcOffsetStd: '+09:30',
    utcOffsetDst: '+10:30',
    abbreviationStd: 'ACST',
    abbreviationDst: 'ACDT',
  },
  {
    tzName: 'Australia/Brisbane',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: 'AEST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/Broken_Hill',
    utcOffsetStd: '+09:30',
    utcOffsetDst: '+10:30',
    abbreviationStd: 'ACST',
    abbreviationDst: 'ACDT',
  },
  {
    tzName: 'Australia/Canberra',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/Currie',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/Darwin',
    utcOffsetStd: '+09:30',
    utcOffsetDst: '',
    abbreviationStd: 'ACST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/Eucla',
    utcOffsetStd: '+08:45',
    utcOffsetDst: '',
    abbreviationStd: '+0845',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/Hobart',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/LHI',
    utcOffsetStd: '+10:30',
    utcOffsetDst: '+11:00',
    abbreviationStd: '+1030',
    abbreviationDst: '+11',
  },
  {
    tzName: 'Australia/Lindeman',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: 'AEST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/Lord_Howe',
    utcOffsetStd: '+10:30',
    utcOffsetDst: '+11:00',
    abbreviationStd: '+1030',
    abbreviationDst: '+11',
  },
  {
    tzName: 'Australia/Melbourne',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/North',
    utcOffsetStd: '+09:30',
    utcOffsetDst: '',
    abbreviationStd: 'ACST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/NSW',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/Perth',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'AWST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/Queensland',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: 'AEST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/South',
    utcOffsetStd: '+09:30',
    utcOffsetDst: '+10:30',
    abbreviationStd: 'ACST',
    abbreviationDst: 'ACDT',
  },
  {
    tzName: 'Australia/Sydney',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/Tasmania',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/Victoria',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '+11:00',
    abbreviationStd: 'AEST',
    abbreviationDst: 'AEDT',
  },
  {
    tzName: 'Australia/West',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'AWST',
    abbreviationDst: '',
  },
  {
    tzName: 'Australia/Yancowinna',
    utcOffsetStd: '+09:30',
    utcOffsetDst: '+10:30',
    abbreviationStd: 'ACST',
    abbreviationDst: 'ACDT',
  },
  {
    tzName: 'Brazil/Acre',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: 'Brazil/DeNoronha',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '',
    abbreviationStd: '-02',
    abbreviationDst: '',
  },
  {
    tzName: 'Brazil/East',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: 'Brazil/West',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: 'Canada/Atlantic',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: 'AST',
    abbreviationDst: 'ADT',
  },
  {
    tzName: 'Canada/Central',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'Canada/Eastern',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'Canada/Mountain',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'Canada/Newfoundland',
    utcOffsetStd: '-03:30',
    utcOffsetDst: '-02:30',
    abbreviationStd: 'NST',
    abbreviationDst: 'NDT',
  },
  {
    tzName: 'Canada/Pacific',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'Canada/Saskatchewan',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'Canada/Yukon',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'CET',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Chile/Continental',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '-03:00',
    abbreviationStd: '-04',
    abbreviationDst: '-03',
  },
  {
    tzName: 'Chile/EasterIsland',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: '-06',
    abbreviationDst: '-05',
  },
  {
    tzName: '  CST6CDT(CST6CDT',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'Cuba',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'EET',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Egypt',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Eire',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+00:00',
    abbreviationStd: 'IST',
    abbreviationDst: 'GMT',
  },
  {
    tzName: 'EST',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: '  EST5EDT(EST5EDT',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'Etc/GMT',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__0(Etc/GMT-0',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__1(Etc/GMT-1',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '',
    abbreviationStd: '+01',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__10(Etc/GMT-10',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__11(Etc/GMT-11',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__12(Etc/GMT-12',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__13(Etc/GMT-13',
    utcOffsetStd: '+13:00',
    utcOffsetDst: '',
    abbreviationStd: '+13',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__14(Etc/GMT-14',
    utcOffsetStd: '+14:00',
    utcOffsetDst: '',
    abbreviationStd: '+14',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__2(Etc/GMT-2',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: '+02',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__3(Etc/GMT-3',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__4(Etc/GMT-4',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__5(Etc/GMT-5',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__6(Etc/GMT-6',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__7(Etc/GMT-7',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__8(Etc/GMT-8',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT__9(Etc/GMT-9',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: '+09',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_0(Etc/GMT+0',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_1(Etc/GMT+1',
    utcOffsetStd: '-01:00',
    utcOffsetDst: '',
    abbreviationStd: '-01',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_10(Etc/GMT+10',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: '-10',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_11(Etc/GMT+11',
    utcOffsetStd: '-11:00',
    utcOffsetDst: '',
    abbreviationStd: '-11',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_12(Etc/GMT+12',
    utcOffsetStd: '-12:00',
    utcOffsetDst: '',
    abbreviationStd: '-12',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_2(Etc/GMT+2',
    utcOffsetStd: '-02:00',
    utcOffsetDst: '',
    abbreviationStd: '-02',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_3(Etc/GMT+3',
    utcOffsetStd: '-03:00',
    utcOffsetDst: '',
    abbreviationStd: '-03',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_4(Etc/GMT+4',
    utcOffsetStd: '-04:00',
    utcOffsetDst: '',
    abbreviationStd: '-04',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_5(Etc/GMT+5',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: '-05',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_6(Etc/GMT+6',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: '-06',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_7(Etc/GMT+7',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: '-07',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_8(Etc/GMT+8',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '',
    abbreviationStd: '-08',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT_9(Etc/GMT+9',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '',
    abbreviationStd: '-09',
    abbreviationDst: '',
  },
  {
    tzName: '  ETC__GMT0(Etc/GMT0',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Etc/Greenwich',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Etc/UCT',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'Etc/Universal',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'Etc/UTC',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'Etc/Zulu',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Amsterdam',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Andorra',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Astrakhan',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Athens',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Belfast',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'Europe/Belgrade',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Berlin',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Bratislava',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Brussels',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Bucharest',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Budapest',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Busingen',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Chisinau',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Copenhagen',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Dublin',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+00:00',
    abbreviationStd: 'IST',
    abbreviationDst: 'GMT',
  },
  {
    tzName: 'Europe/Gibraltar',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Guernsey',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'Europe/Helsinki',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Isle_of_Man',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'Europe/Istanbul',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Jersey',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'Europe/Kaliningrad',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'EET',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Kiev',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Kirov',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'MSK',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Kyiv',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Lisbon',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'Europe/Ljubljana',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/London',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'Europe/Luxembourg',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Madrid',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Malta',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Mariehamn',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Minsk',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Monaco',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Moscow',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'MSK',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Nicosia',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Oslo',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Paris',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Podgorica',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Prague',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Riga',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Rome',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Samara',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/San_Marino',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Sarajevo',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Saratov',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Simferopol',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'MSK',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Skopje',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Sofia',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Stockholm',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Tallinn',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Tirane',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Tiraspol',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Ulyanovsk',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Uzhgorod',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Vaduz',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Vatican',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Vienna',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Vilnius',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Volgograd',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'MSK',
    abbreviationDst: '',
  },
  {
    tzName: 'Europe/Warsaw',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Zagreb',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Europe/Zaporozhye',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'EET',
    abbreviationDst: 'EEST',
  },
  {
    tzName: 'Europe/Zurich',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'GB',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'GB-Eire',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'GMT',
    abbreviationDst: 'BST',
  },
  {
    tzName: 'GMT',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: '  GMT__0(GMT-0',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: '  GMT_0(GMT+0',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: '  GMT0(GMT0',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Greenwich',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Hongkong',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'HKT',
    abbreviationDst: '',
  },
  {
    tzName: 'HST',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: 'HST',
    abbreviationDst: '',
  },
  {
    tzName: 'Iceland',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'GMT',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Antananarivo',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Chagos',
    utcOffsetStd: '+06:00',
    utcOffsetDst: '',
    abbreviationStd: '+06',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Christmas',
    utcOffsetStd: '+07:00',
    utcOffsetDst: '',
    abbreviationStd: '+07',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Cocos',
    utcOffsetStd: '+06:30',
    utcOffsetDst: '',
    abbreviationStd: '+0630',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Comoro',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Kerguelen',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Mahe',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Maldives',
    utcOffsetStd: '+05:00',
    utcOffsetDst: '',
    abbreviationStd: '+05',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Mauritius',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Mayotte',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'EAT',
    abbreviationDst: '',
  },
  {
    tzName: 'Indian/Reunion',
    utcOffsetStd: '+04:00',
    utcOffsetDst: '',
    abbreviationStd: '+04',
    abbreviationDst: '',
  },
  {
    tzName: 'Iran',
    utcOffsetStd: '+03:30',
    utcOffsetDst: '',
    abbreviationStd: '+0330',
    abbreviationDst: '',
  },
  {
    tzName: 'Israel',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '+03:00',
    abbreviationStd: 'IST',
    abbreviationDst: 'IDT',
  },
  {
    tzName: 'Jamaica',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '',
    abbreviationStd: 'EST',
    abbreviationDst: '',
  },
  {
    tzName: 'Japan',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: 'JST',
    abbreviationDst: '',
  },
  {
    tzName: 'Kwajalein',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Libya',
    utcOffsetStd: '+02:00',
    utcOffsetDst: '',
    abbreviationStd: 'EET',
    abbreviationDst: '',
  },
  {
    tzName: 'MET',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'MET',
    abbreviationDst: 'MEST',
  },
  {
    tzName: 'Mexico/BajaNorte',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'Mexico/BajaSur',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'Mexico/General',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'MST',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: '  MST7MDT(MST7MDT',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'Navajo',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'NZ',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '+13:00',
    abbreviationStd: 'NZST',
    abbreviationDst: 'NZDT',
  },
  {
    tzName: 'NZ-CHAT',
    utcOffsetStd: '+12:45',
    utcOffsetDst: '+13:45',
    abbreviationStd: '+1245',
    abbreviationDst: '+1345',
  },
  {
    tzName: 'Pacific/Apia',
    utcOffsetStd: '+13:00',
    utcOffsetDst: '',
    abbreviationStd: '+13',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Auckland',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '+13:00',
    abbreviationStd: 'NZST',
    abbreviationDst: 'NZDT',
  },
  {
    tzName: 'Pacific/Bougainville',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Chatham',
    utcOffsetStd: '+12:45',
    utcOffsetDst: '+13:45',
    abbreviationStd: '+1245',
    abbreviationDst: '+1345',
  },
  {
    tzName: 'Pacific/Chuuk',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Easter',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: '-06',
    abbreviationDst: '-05',
  },
  {
    tzName: 'Pacific/Efate',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Enderbury',
    utcOffsetStd: '+13:00',
    utcOffsetDst: '',
    abbreviationStd: '+13',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Fakaofo',
    utcOffsetStd: '+13:00',
    utcOffsetDst: '',
    abbreviationStd: '+13',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Fiji',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Funafuti',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Galapagos',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '',
    abbreviationStd: '-06',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Gambier',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '',
    abbreviationStd: '-09',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Guadalcanal',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Guam',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: 'ChST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Honolulu',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: 'HST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Johnston',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: 'HST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Kanton',
    utcOffsetStd: '+13:00',
    utcOffsetDst: '',
    abbreviationStd: '+13',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Kiritimati',
    utcOffsetStd: '+14:00',
    utcOffsetDst: '',
    abbreviationStd: '+14',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Kosrae',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Kwajalein',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Majuro',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Marquesas',
    utcOffsetStd: '-09:30',
    utcOffsetDst: '',
    abbreviationStd: '-0930',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Midway',
    utcOffsetStd: '-11:00',
    utcOffsetDst: '',
    abbreviationStd: 'SST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Nauru',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Niue',
    utcOffsetStd: '-11:00',
    utcOffsetDst: '',
    abbreviationStd: '-11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Norfolk',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '+12:00',
    abbreviationStd: '+11',
    abbreviationDst: '+12',
  },
  {
    tzName: 'Pacific/Noumea',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Pago_Pago',
    utcOffsetStd: '-11:00',
    utcOffsetDst: '',
    abbreviationStd: 'SST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Palau',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: '+09',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Pitcairn',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '',
    abbreviationStd: '-08',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Pohnpei',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Ponape',
    utcOffsetStd: '+11:00',
    utcOffsetDst: '',
    abbreviationStd: '+11',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Port_Moresby',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Rarotonga',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: '-10',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Saipan',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: 'ChST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Samoa',
    utcOffsetStd: '-11:00',
    utcOffsetDst: '',
    abbreviationStd: 'SST',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Tahiti',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: '-10',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Tarawa',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Tongatapu',
    utcOffsetStd: '+13:00',
    utcOffsetDst: '',
    abbreviationStd: '+13',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Truk',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Wake',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Wallis',
    utcOffsetStd: '+12:00',
    utcOffsetDst: '',
    abbreviationStd: '+12',
    abbreviationDst: '',
  },
  {
    tzName: 'Pacific/Yap',
    utcOffsetStd: '+10:00',
    utcOffsetDst: '',
    abbreviationStd: '+10',
    abbreviationDst: '',
  },
  {
    tzName: 'Poland',
    utcOffsetStd: '+01:00',
    utcOffsetDst: '+02:00',
    abbreviationStd: 'CET',
    abbreviationDst: 'CEST',
  },
  {
    tzName: 'Portugal',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'PRC',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: '  PST8PDT(PST8PDT',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'ROC',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: 'CST',
    abbreviationDst: '',
  },
  {
    tzName: 'ROK',
    utcOffsetStd: '+09:00',
    utcOffsetDst: '',
    abbreviationStd: 'KST',
    abbreviationDst: '',
  },
  {
    tzName: 'Singapore',
    utcOffsetStd: '+08:00',
    utcOffsetDst: '',
    abbreviationStd: '+08',
    abbreviationDst: '',
  },
  {
    tzName: 'Turkey',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: '+03',
    abbreviationDst: '',
  },
  {
    tzName: 'UCT',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'Universal',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'US/Alaska',
    utcOffsetStd: '-09:00',
    utcOffsetDst: '-08:00',
    abbreviationStd: 'AKST',
    abbreviationDst: 'AKDT',
  },
  {
    tzName: 'US/Aleutian',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '-09:00',
    abbreviationStd: 'HST',
    abbreviationDst: 'HDT',
  },
  {
    tzName: 'US/Arizona',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '',
    abbreviationStd: 'MST',
    abbreviationDst: '',
  },
  {
    tzName: 'US/Central',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'US/East-Indiana',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'US/Eastern',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'US/Hawaii',
    utcOffsetStd: '-10:00',
    utcOffsetDst: '',
    abbreviationStd: 'HST',
    abbreviationDst: '',
  },
  {
    tzName: 'US/Indiana-Starke',
    utcOffsetStd: '-06:00',
    utcOffsetDst: '-05:00',
    abbreviationStd: 'CST',
    abbreviationDst: 'CDT',
  },
  {
    tzName: 'US/Michigan',
    utcOffsetStd: '-05:00',
    utcOffsetDst: '-04:00',
    abbreviationStd: 'EST',
    abbreviationDst: 'EDT',
  },
  {
    tzName: 'US/Mountain',
    utcOffsetStd: '-07:00',
    utcOffsetDst: '-06:00',
    abbreviationStd: 'MST',
    abbreviationDst: 'MDT',
  },
  {
    tzName: 'US/Pacific',
    utcOffsetStd: '-08:00',
    utcOffsetDst: '-07:00',
    abbreviationStd: 'PST',
    abbreviationDst: 'PDT',
  },
  {
    tzName: 'US/Samoa',
    utcOffsetStd: '-11:00',
    utcOffsetDst: '',
    abbreviationStd: 'SST',
    abbreviationDst: '',
  },
  {
    tzName: 'UTC',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
  {
    tzName: 'W-SU',
    utcOffsetStd: '+03:00',
    utcOffsetDst: '',
    abbreviationStd: 'MSK',
    abbreviationDst: '',
  },
  {
    tzName: 'WET',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '+01:00',
    abbreviationStd: 'WET',
    abbreviationDst: 'WEST',
  },
  {
    tzName: 'Zulu',
    utcOffsetStd: '+00:00',
    utcOffsetDst: '',
    abbreviationStd: 'UTC',
    abbreviationDst: '',
  },
] as const;

/** Commonly used timezones for quick access. */
export const COMMON_TIMEZONES: readonly string[] = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Anchorage',
  'Pacific/Honolulu',
  'America/Toronto',
  'America/Vancouver',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Moscow',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Kolkata',
  'Asia/Dubai',
  'Australia/Sydney',
  'Pacific/Auckland',
  'Etc/UTC',
] as const;

/** Look up timezone info by IANA name. */
export function findTimezone(tzName: string): IanaTimezoneInfo | undefined {
  return IANA_TIMEZONES.find((tz) => tz.tzName === tzName);
}

/** Format a timezone for display: "America/New_York (EST, UTC-05:00)". */
export function formatTimezoneLabel(tz: IanaTimezoneInfo): string {
  const parts = [tz.tzName.replace(/_/g, ' ')];
  if (tz.abbreviationStd) {
    parts.push(`(${tz.abbreviationStd}, UTC${tz.utcOffsetStd})`);
  } else {
    parts.push(`(UTC${tz.utcOffsetStd})`);
  }
  return parts.join(' ');
}

/** Search timezones by name, abbreviation, or offset. Returns matches sorted by relevance. */
export function searchTimezones(query: string, limit = 20): IanaTimezoneInfo[] {
  if (!query.trim())
    return IANA_TIMEZONES.filter((tz) => COMMON_TIMEZONES.includes(tz.tzName)).slice(0, limit);

  const q = query.toLowerCase().replace(/_/g, ' ');
  const scored = IANA_TIMEZONES.map((tz) => {
    const name = tz.tzName.toLowerCase().replace(/_/g, ' ');
    const abbr = tz.abbreviationStd.toLowerCase();
    let score = 0;
    if (name === q) score = 100;
    else if (name.startsWith(q)) score = 80;
    else if (abbr === q) score = 70;
    else if (name.includes(q)) score = 50;
    else if (abbr.includes(q)) score = 30;
    else if (tz.utcOffsetStd.includes(query)) score = 20;
    return { tz, score };
  })
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, limit).map((s) => s.tz);
}
