import type { Item } from '@/extras/types/reference/items/item-domain';

const now = Date.now();

const timeCoordinates = () => ({ recordedAsOf: now, effectiveAsOf: now });

export const mockPublishedItems: Item[] = [
  {
    entityId: 'ITEM-0001',
    recordId: 'rec-0001',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Hex Bolt M8x40 Zinc Plated',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'FASTENER', subType: 'BOLT' },
    useCase: 'General assembly and mounting',
    locator: { facility: 'Main Warehouse', department: 'Hardware', location: 'Aisle 3-B' },
    internalSKU: 'HW-BOLT-M8-40',
    generalLedgerCode: 'GL-5100',
    minQuantity: { amount: 100, unit: 'EACH' },
    notes: 'Standard DIN 933 specification',
    cardNotesDefault: 'Check torque spec before use',
    taxable: true,
    primarySupply: {
      supplier: 'Fastenal',
      name: 'M8x40mm Hex Bolt',
      sku: 'FAS-HB-M840',
      orderMechanism: 'ONLINE',
      url: 'https://www.fastenal.com/products/fasteners/bolts/hex-bolts',
      orderQuantity: { amount: 500, unit: 'EACH' },
      unitCost: { value: 0.35, currency: 'USD' },
      orderCost: { value: 175.0, currency: 'USD' },
    },
    secondarySupply: {
      supplier: 'Grainger',
      name: 'Hex Bolt M8x40',
      sku: 'GRA-234567',
      orderMechanism: 'PURCHASE_ORDER',
      orderQuantity: { amount: 250, unit: 'EACH' },
      unitCost: { value: 0.42, currency: 'USD' },
      orderCost: { value: 105.0, currency: 'USD' },
    },
    defaultSupply: 'Fastenal',
    cardSize: 'MEDIUM',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'GRAY',
  },
  {
    entityId: 'ITEM-0002',
    recordId: 'rec-0002',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Bearing SKF 6204-2RS',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'MECHANICAL', subType: 'BEARING' },
    useCase: 'Motor shafts and rotating equipment',
    locator: { facility: 'Main Warehouse', department: 'Mechanical Parts', location: 'Shelf 12-A' },
    internalSKU: 'MP-BEAR-6204',
    generalLedgerCode: 'GL-5200',
    minQuantity: { amount: 10, unit: 'EACH' },
    notes: 'Deep groove ball bearing with rubber seals',
    cardNotesDefault: 'Store in dry location',
    taxable: true,
    primarySupply: {
      supplier: 'Motion Industries',
      name: 'SKF 6204-2RS Ball Bearing',
      sku: 'SKF-6204-2RS',
      orderMechanism: 'ONLINE',
      url: 'https://www.motionindustries.com/skf-bearings',
      orderQuantity: { amount: 24, unit: 'EACH' },
      unitCost: { value: 12.45, currency: 'USD' },
      orderCost: { value: 298.8, currency: 'USD' },
    },
    defaultSupply: 'Motion Industries',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'BLUE',
  },
  {
    entityId: 'ITEM-0003',
    recordId: 'rec-0003',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Wire AWG 18 Black Stranded',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'ELECTRICAL', subType: 'WIRE' },
    useCase: 'Control panel wiring',
    locator: { facility: 'Main Warehouse', department: 'Electrical', location: 'Cabinet E-5' },
    internalSKU: 'EL-WIRE-18BLK',
    generalLedgerCode: 'GL-5300',
    minQuantity: { amount: 500, unit: 'FOOT' },
    notes: '600V rated, UL1015 compliant',
    cardNotesDefault: 'Cut to required length',
    taxable: true,
    primarySupply: {
      supplier: 'Anixter',
      name: 'AWG 18 Black Stranded Wire',
      sku: 'ANX-W18BK',
      orderMechanism: 'ONLINE',
      url: 'https://www.anixter.com/wire-cable',
      orderQuantity: { amount: 1000, unit: 'FOOT' },
      unitCost: { value: 0.22, currency: 'USD' },
      orderCost: { value: 220.0, currency: 'USD' },
    },
    secondarySupply: {
      supplier: 'Digi-Key',
      name: '18AWG Black Wire',
      sku: 'DK-W18B-1000',
      orderMechanism: 'ONLINE',
      orderQuantity: { amount: 500, unit: 'FOOT' },
      unitCost: { value: 0.28, currency: 'USD' },
      orderCost: { value: 140.0, currency: 'USD' },
    },
    defaultSupply: 'Anixter',
    cardSize: 'LARGE',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'BLACK',
  },
  {
    entityId: 'ITEM-0004',
    recordId: 'rec-0004',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Hydraulic Hose 1/2" x 10ft',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'HYDRAULIC', subType: 'HOSE' },
    useCase: 'Hydraulic system connections',
    locator: { facility: 'Main Warehouse', department: 'Hydraulics', location: 'Rack H-3' },
    internalSKU: 'HY-HOSE-05-10',
    generalLedgerCode: 'GL-5400',
    minQuantity: { amount: 5, unit: 'EACH' },
    notes: '3000 PSI working pressure, SAE 100R2AT',
    cardNotesDefault: 'Inspect for damage before installation',
    taxable: true,
    primarySupply: {
      supplier: 'Parker Hannifin',
      name: '1/2" Hydraulic Hose Assembly',
      sku: 'PKR-H05-10',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.parker.com/hydraulic-hose',
      orderQuantity: { amount: 10, unit: 'EACH' },
      unitCost: { value: 45.75, currency: 'USD' },
      orderCost: { value: 457.5, currency: 'USD' },
    },
    defaultSupply: 'Parker Hannifin',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'RED',
  },
  {
    entityId: 'ITEM-0005',
    recordId: 'rec-0005',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Safety Gloves Cut-Resistant L',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'PPE', subType: 'GLOVES' },
    useCase: 'Worker hand protection',
    locator: {
      facility: 'Main Warehouse',
      department: 'Safety Equipment',
      location: 'Storage S-2',
    },
    internalSKU: 'PPE-GLOVE-CRL',
    generalLedgerCode: 'GL-5500',
    minQuantity: { amount: 50, unit: 'PAIR' },
    notes: 'ANSI A3 cut resistance, EN388 certified',
    cardNotesDefault: 'Replace when worn or damaged',
    taxable: false,
    primarySupply: {
      supplier: 'Uline',
      name: 'Cut-Resistant Gloves - Large',
      sku: 'ULN-GLV-CRL',
      orderMechanism: 'ONLINE',
      url: 'https://www.uline.com/safety-gloves',
      orderQuantity: { amount: 144, unit: 'PAIR' },
      unitCost: { value: 8.95, currency: 'USD' },
      orderCost: { value: 1288.8, currency: 'USD' },
    },
    defaultSupply: 'Uline',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'YELLOW',
  },
  {
    entityId: 'ITEM-0006',
    recordId: 'rec-0006',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Pneumatic Cylinder 2" Bore x 6" Stroke',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'PNEUMATIC', subType: 'CYLINDER' },
    useCase: 'Automated assembly equipment',
    locator: { facility: 'Main Warehouse', department: 'Pneumatics', location: 'Zone P-4' },
    internalSKU: 'PN-CYL-2X6',
    generalLedgerCode: 'GL-5600',
    minQuantity: { amount: 2, unit: 'EACH' },
    notes: 'Double-acting, 150 PSI max pressure',
    cardNotesDefault: 'Verify mounting configuration',
    taxable: true,
    primarySupply: {
      supplier: 'SMC Corporation',
      name: 'Pneumatic Cylinder 2x6',
      sku: 'SMC-CYL-2X6',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.smcworld.com/pneumatic-cylinders',
      orderQuantity: { amount: 4, unit: 'EACH' },
      unitCost: { value: 185.5, currency: 'USD' },
      orderCost: { value: 742.0, currency: 'USD' },
    },
    defaultSupply: 'SMC Corporation',
    cardSize: 'LARGE',
    labelSize: 'LARGE',
    breadcrumbSize: 'LARGE',
    color: 'GREEN',
  },
  {
    entityId: 'ITEM-0007',
    recordId: 'rec-0007',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'PLC Input Module 16-Channel',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'ELECTRICAL', subType: 'CONTROL' },
    useCase: 'Process control systems',
    locator: { facility: 'Main Warehouse', department: 'Controls', location: 'Cabinet C-1' },
    internalSKU: 'CT-PLC-IN16',
    generalLedgerCode: 'GL-5700',
    minQuantity: { amount: 1, unit: 'EACH' },
    notes: 'Allen-Bradley compatible, 24VDC input',
    cardNotesDefault: 'Configure before installation',
    taxable: true,
    primarySupply: {
      supplier: 'Rockwell Automation',
      name: '1746-IB16 Input Module',
      sku: 'RAL-1746-IB16',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.rockwellautomation.com/plc-modules',
      orderQuantity: { amount: 2, unit: 'EACH' },
      unitCost: { value: 325.0, currency: 'USD' },
      orderCost: { value: 650.0, currency: 'USD' },
    },
    defaultSupply: 'Rockwell Automation',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'BLUE',
  },
  {
    entityId: 'ITEM-0008',
    recordId: 'rec-0008',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Industrial Lubricant 5-Gallon',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'CHEMICAL', subType: 'LUBRICANT' },
    useCase: 'Machine maintenance',
    locator: { facility: 'Main Warehouse', department: 'Chemicals', location: 'Hazmat Zone 2' },
    internalSKU: 'CH-LUB-5GAL',
    generalLedgerCode: 'GL-5800',
    minQuantity: { amount: 2, unit: 'GALLON' },
    notes: 'ISO VG 68, food-grade approved',
    cardNotesDefault: 'Use proper PPE when handling',
    taxable: true,
    primarySupply: {
      supplier: 'Mobil Oil',
      name: 'Mobil DTE 24 Hydraulic Oil',
      sku: 'MOB-DTE24-5G',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.mobil.com/industrial-lubricants',
      orderQuantity: { amount: 10, unit: 'GALLON' },
      unitCost: { value: 28.5, currency: 'USD' },
      orderCost: { value: 285.0, currency: 'USD' },
    },
    defaultSupply: 'Mobil Oil',
    cardSize: 'MEDIUM',
    labelSize: 'LARGE',
    breadcrumbSize: 'MEDIUM',
    color: 'ORANGE',
  },
  {
    entityId: 'ITEM-0009',
    recordId: 'rec-0009',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'V-Belt B Section 60" Length',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'MECHANICAL', subType: 'BELT' },
    useCase: 'Power transmission',
    locator: { facility: 'Main Warehouse', department: 'Power Transmission', location: 'Bin PT-8' },
    internalSKU: 'PT-VBELT-B60',
    generalLedgerCode: 'GL-5900',
    minQuantity: { amount: 5, unit: 'EACH' },
    notes: 'Standard B section, wrapped construction',
    cardNotesDefault: 'Check pulley alignment',
    taxable: true,
    primarySupply: {
      supplier: 'Gates Corporation',
      name: 'Hi-Power II V-Belt B60',
      sku: 'GAT-B60',
      orderMechanism: 'ONLINE',
      url: 'https://www.gates.com/v-belts',
      orderQuantity: { amount: 10, unit: 'EACH' },
      unitCost: { value: 15.75, currency: 'USD' },
      orderCost: { value: 157.5, currency: 'USD' },
    },
    defaultSupply: 'Gates Corporation',
    cardSize: 'MEDIUM',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'BLACK',
  },
  {
    entityId: 'ITEM-0010',
    recordId: 'rec-0010',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Stainless Steel Sheet 4x8 16GA',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'RAW_MATERIAL', subType: 'METAL' },
    useCase: 'Fabrication projects',
    locator: { facility: 'Main Warehouse', department: 'Raw Materials', location: 'Rack RM-1' },
    internalSKU: 'RM-SS-4X8-16',
    generalLedgerCode: 'GL-6000',
    minQuantity: { amount: 2, unit: 'EACH' },
    notes: '304 stainless steel, 2B finish',
    cardNotesDefault: 'Handle with care to avoid scratches',
    taxable: true,
    primarySupply: {
      supplier: 'Ryerson Steel',
      name: 'SS 304 Sheet 4x8x16GA',
      sku: 'RYR-SS304-4816',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.ryerson.com/stainless-steel',
      orderQuantity: { amount: 5, unit: 'EACH' },
      unitCost: { value: 245.0, currency: 'USD' },
      orderCost: { value: 1225.0, currency: 'USD' },
    },
    defaultSupply: 'Ryerson Steel',
    cardSize: 'X_LARGE',
    labelSize: 'LARGE',
    breadcrumbSize: 'LARGE',
    color: 'GRAY',
  },
  {
    entityId: 'ITEM-0011',
    recordId: 'rec-0011',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Proximity Sensor 12mm PNP',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'SENSOR', subType: 'PROXIMITY' },
    useCase: 'Position detection',
    locator: { facility: 'Main Warehouse', department: 'Sensors', location: 'Drawer S-15' },
    internalSKU: 'SN-PROX-12PNP',
    generalLedgerCode: 'GL-6100',
    minQuantity: { amount: 10, unit: 'EACH' },
    notes: 'M12 threaded, 4mm sensing range, NO output',
    cardNotesDefault: 'Test before final installation',
    taxable: true,
    primarySupply: {
      supplier: 'Omron',
      name: 'E2E-X3D1-N Proximity Sensor',
      sku: 'OMR-E2E-X3D1',
      orderMechanism: 'ONLINE',
      url: 'https://www.omron.com/proximity-sensors',
      orderQuantity: { amount: 20, unit: 'EACH' },
      unitCost: { value: 42.5, currency: 'USD' },
      orderCost: { value: 850.0, currency: 'USD' },
    },
    secondarySupply: {
      supplier: 'Automation Direct',
      name: '12mm Proximity Sensor PNP',
      sku: 'AD-PS12PNP',
      orderMechanism: 'ONLINE',
      orderQuantity: { amount: 10, unit: 'EACH' },
      unitCost: { value: 38.9, currency: 'USD' },
      orderCost: { value: 389.0, currency: 'USD' },
    },
    defaultSupply: 'Automation Direct',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'GREEN',
  },
  {
    entityId: 'ITEM-0012',
    recordId: 'rec-0012',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Chain Roller #40 10ft',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'MECHANICAL', subType: 'CHAIN' },
    useCase: 'Conveyor systems',
    locator: { facility: 'Main Warehouse', department: 'Conveyors', location: 'Bin CV-3' },
    internalSKU: 'CV-CHAIN-40-10',
    generalLedgerCode: 'GL-6200',
    minQuantity: { amount: 20, unit: 'FOOT' },
    notes: 'ANSI #40 standard roller chain',
    cardNotesDefault: 'Lubricate after installation',
    taxable: true,
    primarySupply: {
      supplier: 'Tsubaki',
      name: 'RS40 Roller Chain',
      sku: 'TSU-RS40-10',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.tsubaki.com/roller-chain',
      orderQuantity: { amount: 100, unit: 'FOOT' },
      unitCost: { value: 3.25, currency: 'USD' },
      orderCost: { value: 325.0, currency: 'USD' },
    },
    defaultSupply: 'Tsubaki',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'GRAY',
  },
  {
    entityId: 'ITEM-0013',
    recordId: 'rec-0013',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Paint Epoxy Gray Gallon',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'CHEMICAL', subType: 'COATING' },
    useCase: 'Equipment finishing',
    locator: { facility: 'Main Warehouse', department: 'Paint Shop', location: 'Cabinet PS-4' },
    internalSKU: 'PS-PAINT-EGRY-1G',
    generalLedgerCode: 'GL-6300',
    minQuantity: { amount: 2, unit: 'GALLON' },
    notes: 'Two-part epoxy, RAL 7035 light gray',
    cardNotesDefault: 'Mix according to manufacturer instructions',
    taxable: true,
    primarySupply: {
      supplier: 'Sherwin-Williams',
      name: 'Industrial Epoxy Paint Gray',
      sku: 'SHW-EP-GRY-1G',
      orderMechanism: 'IN_STORE',
      url: 'https://www.sherwin-williams.com/industrial',
      orderQuantity: { amount: 5, unit: 'GALLON' },
      unitCost: { value: 68.5, currency: 'USD' },
      orderCost: { value: 342.5, currency: 'USD' },
    },
    defaultSupply: 'Sherwin-Williams',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'GRAY',
  },
  {
    entityId: 'ITEM-0014',
    recordId: 'rec-0014',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Limit Switch SPDT Roller',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'ELECTRICAL', subType: 'SWITCH' },
    useCase: 'Position limit detection',
    locator: { facility: 'Main Warehouse', department: 'Electrical', location: 'Box E-12' },
    internalSKU: 'EL-LS-SPDT-R',
    generalLedgerCode: 'GL-6400',
    minQuantity: { amount: 5, unit: 'EACH' },
    notes: 'Heavy-duty, 10A @ 250VAC',
    cardNotesDefault: 'Mount securely to prevent movement',
    taxable: true,
    primarySupply: {
      supplier: 'Honeywell',
      name: 'MICRO SWITCH LSZ Series',
      sku: 'HON-LSZ-SPDT',
      orderMechanism: 'ONLINE',
      url: 'https://www.honeywell.com/limit-switches',
      orderQuantity: { amount: 10, unit: 'EACH' },
      unitCost: { value: 28.75, currency: 'USD' },
      orderCost: { value: 287.5, currency: 'USD' },
    },
    defaultSupply: 'Honeywell',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'BLUE',
  },
  {
    entityId: 'ITEM-0015',
    recordId: 'rec-0015',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Caster Wheel 4" Swivel Brake',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'HARDWARE', subType: 'CASTER' },
    useCase: 'Mobile equipment',
    locator: { facility: 'Main Warehouse', department: 'Hardware', location: 'Shelf H-6' },
    internalSKU: 'HW-CAST-4SWB',
    generalLedgerCode: 'GL-6500',
    minQuantity: { amount: 20, unit: 'EACH' },
    notes: '300 lb capacity, polyurethane wheel',
    cardNotesDefault: 'Install in sets of 4 for stability',
    taxable: true,
    primarySupply: {
      supplier: 'Albion',
      name: '4" Swivel Caster with Brake',
      sku: 'ALB-4SWBK',
      orderMechanism: 'ONLINE',
      url: 'https://www.albioncasters.com/swivel-brake',
      orderQuantity: { amount: 40, unit: 'EACH' },
      unitCost: { value: 18.25, currency: 'USD' },
      orderCost: { value: 730.0, currency: 'USD' },
    },
    defaultSupply: 'Albion',
    cardSize: 'MEDIUM',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'BLACK',
  },
  {
    entityId: 'ITEM-0016',
    recordId: 'rec-0016',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Pressure Gauge 0-200 PSI',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'INSTRUMENT', subType: 'GAUGE' },
    useCase: 'Pressure monitoring',
    locator: { facility: 'Main Warehouse', department: 'Instrumentation', location: 'Cabinet I-2' },
    internalSKU: 'IN-PG-200PSI',
    generalLedgerCode: 'GL-6600',
    minQuantity: { amount: 3, unit: 'EACH' },
    notes: '2.5" dial, 1/4" NPT bottom mount',
    cardNotesDefault: 'Verify pressure range before installation',
    taxable: true,
    primarySupply: {
      supplier: 'Ashcroft',
      name: 'Pressure Gauge 0-200 PSI',
      sku: 'ASH-PG-200',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.ashcroft.com/pressure-gauges',
      orderQuantity: { amount: 6, unit: 'EACH' },
      unitCost: { value: 55.0, currency: 'USD' },
      orderCost: { value: 330.0, currency: 'USD' },
    },
    defaultSupply: 'Ashcroft',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'WHITE',
  },
  {
    entityId: 'ITEM-0017',
    recordId: 'rec-0017',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Welding Rod E7018 1/8" 10lb',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'CONSUMABLE', subType: 'WELDING' },
    useCase: 'Structural welding',
    locator: { facility: 'Main Warehouse', department: 'Welding', location: 'Cabinet W-1' },
    internalSKU: 'WD-ROD-7018-18',
    generalLedgerCode: 'GL-6700',
    minQuantity: { amount: 10, unit: 'POUND' },
    notes: 'Low hydrogen electrode, AC/DC compatible',
    cardNotesDefault: 'Store in rod oven at 250°F',
    taxable: true,
    primarySupply: {
      supplier: 'Lincoln Electric',
      name: 'Fleetweld 7018 Electrode',
      sku: 'LIN-7018-18-10',
      orderMechanism: 'ONLINE',
      url: 'https://www.lincolnelectric.com/welding-electrodes',
      orderQuantity: { amount: 50, unit: 'POUND' },
      unitCost: { value: 4.85, currency: 'USD' },
      orderCost: { value: 242.5, currency: 'USD' },
    },
    defaultSupply: 'Lincoln Electric',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'RED',
  },
  {
    entityId: 'ITEM-0018',
    recordId: 'rec-0018',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Fuse Cartridge 30A 600V',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'ELECTRICAL', subType: 'FUSE' },
    useCase: 'Circuit protection',
    locator: { facility: 'Main Warehouse', department: 'Electrical', location: 'Drawer E-8' },
    internalSKU: 'EL-FUSE-30A-600',
    generalLedgerCode: 'GL-6800',
    minQuantity: { amount: 20, unit: 'EACH' },
    notes: 'Class CC, time-delay, UL listed',
    cardNotesDefault: 'Match fuse rating to circuit requirements',
    taxable: true,
    primarySupply: {
      supplier: 'Littelfuse',
      name: 'FLNR Series 30A Fuse',
      sku: 'LIT-FLNR-30',
      orderMechanism: 'ONLINE',
      url: 'https://www.littelfuse.com/fuses',
      orderQuantity: { amount: 100, unit: 'EACH' },
      unitCost: { value: 6.25, currency: 'USD' },
      orderCost: { value: 625.0, currency: 'USD' },
    },
    defaultSupply: 'Littelfuse',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'YELLOW',
  },
  {
    entityId: 'ITEM-0019',
    recordId: 'rec-0019',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'O-Ring Viton 2-116 Dash',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'SEAL', subType: 'O_RING' },
    useCase: 'Fluid sealing',
    locator: { facility: 'Main Warehouse', department: 'Seals', location: 'Organizer O-5' },
    internalSKU: 'SL-ORING-V116',
    generalLedgerCode: 'GL-6900',
    minQuantity: { amount: 50, unit: 'EACH' },
    notes: 'Viton material, -15°F to 400°F',
    cardNotesDefault: 'Check groove dimensions',
    taxable: true,
    primarySupply: {
      supplier: 'Parker O-Ring',
      name: 'Viton O-Ring 2-116',
      sku: 'PKR-V-2-116',
      orderMechanism: 'ONLINE',
      url: 'https://www.parker.com/o-rings',
      orderQuantity: { amount: 100, unit: 'EACH' },
      unitCost: { value: 1.85, currency: 'USD' },
      orderCost: { value: 185.0, currency: 'USD' },
    },
    secondarySupply: {
      supplier: 'Apple Rubber',
      name: '2-116 Viton O-Ring',
      sku: 'APL-2116-V',
      orderMechanism: 'ONLINE',
      orderQuantity: { amount: 50, unit: 'EACH' },
      unitCost: { value: 2.1, currency: 'USD' },
      orderCost: { value: 105.0, currency: 'USD' },
    },
    defaultSupply: 'Parker O-Ring',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'BLACK',
  },
  {
    entityId: 'ITEM-0020',
    recordId: 'rec-0020',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Servo Motor 1kW 3000 RPM',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'MOTOR', subType: 'SERVO' },
    useCase: 'Precision motion control',
    locator: { facility: 'Main Warehouse', department: 'Motors', location: 'Shelf M-3' },
    internalSKU: 'MT-SERVO-1K-3K',
    generalLedgerCode: 'GL-7000',
    minQuantity: { amount: 1, unit: 'EACH' },
    notes: '230VAC 3-phase, encoder feedback',
    cardNotesDefault: 'Requires matched drive amplifier',
    taxable: true,
    primarySupply: {
      supplier: 'Yaskawa',
      name: 'Sigma-7 Servo Motor 1kW',
      sku: 'YAS-SG7-1K',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.yaskawa.com/servo-motors',
      orderQuantity: { amount: 2, unit: 'EACH' },
      unitCost: { value: 1450.0, currency: 'USD' },
      orderCost: { value: 2900.0, currency: 'USD' },
    },
    defaultSupply: 'Yaskawa',
    cardSize: 'LARGE',
    labelSize: 'LARGE',
    breadcrumbSize: 'LARGE',
    color: 'BLUE',
  },
  {
    entityId: 'ITEM-0021',
    recordId: 'rec-0021',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Air Filter Element 10 Micron',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'FILTRATION', subType: 'AIR_FILTER' },
    useCase: 'Compressed air system',
    locator: { facility: 'Main Warehouse', department: 'Pneumatics', location: 'Bin P-9' },
    internalSKU: 'PN-FILT-10M',
    generalLedgerCode: 'GL-7100',
    minQuantity: { amount: 10, unit: 'EACH' },
    notes: 'Coalescing filter, 99.97% efficiency',
    cardNotesDefault: 'Replace every 6 months',
    taxable: true,
    primarySupply: {
      supplier: 'Parker Filtration',
      name: '10 Micron Filter Element',
      sku: 'PKR-FE-10M',
      orderMechanism: 'ONLINE',
      url: 'https://www.parker.com/air-filters',
      orderQuantity: { amount: 12, unit: 'EACH' },
      unitCost: { value: 32.5, currency: 'USD' },
      orderCost: { value: 390.0, currency: 'USD' },
    },
    defaultSupply: 'Parker Filtration',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'WHITE',
  },
  {
    entityId: 'ITEM-0022',
    recordId: 'rec-0022',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Cutting Fluid Soluble 5-Gallon',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'CHEMICAL', subType: 'COOLANT' },
    useCase: 'Machine tool coolant',
    locator: { facility: 'Main Warehouse', department: 'Machine Shop', location: 'Tank Area T-1' },
    internalSKU: 'MS-COOL-SOL-5G',
    generalLedgerCode: 'GL-7200',
    minQuantity: { amount: 10, unit: 'GALLON' },
    notes: 'Semi-synthetic, 20:1 mix ratio',
    cardNotesDefault: 'Monitor concentration weekly',
    taxable: true,
    primarySupply: {
      supplier: 'Master Chemical',
      name: 'TRIM SC210 Coolant',
      sku: 'MST-SC210-5G',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.masterchemical.com/coolants',
      orderQuantity: { amount: 20, unit: 'GALLON' },
      unitCost: { value: 42.75, currency: 'USD' },
      orderCost: { value: 855.0, currency: 'USD' },
    },
    defaultSupply: 'Master Chemical',
    cardSize: 'MEDIUM',
    labelSize: 'LARGE',
    breadcrumbSize: 'MEDIUM',
    color: 'GREEN',
  },
  {
    entityId: 'ITEM-0023',
    recordId: 'rec-0023',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Cable Tie 8" Natural 100pk',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'HARDWARE', subType: 'CABLE_TIE' },
    useCase: 'Wire management',
    locator: { facility: 'Main Warehouse', department: 'Electrical', location: 'Bin E-20' },
    internalSKU: 'EL-TIE-8NAT-100',
    generalLedgerCode: 'GL-7300',
    minQuantity: { amount: 500, unit: 'EACH' },
    notes: 'Nylon 6/6, 50 lb tensile strength',
    cardNotesDefault: 'Do not over-tighten',
    taxable: true,
    primarySupply: {
      supplier: 'Thomas & Betts',
      name: '8" Cable Ties Natural',
      sku: 'TB-CT8N-100',
      orderMechanism: 'ONLINE',
      url: 'https://www.tnb.com/cable-ties',
      orderQuantity: { amount: 1000, unit: 'EACH' },
      unitCost: { value: 0.08, currency: 'USD' },
      orderCost: { value: 80.0, currency: 'USD' },
    },
    defaultSupply: 'Thomas & Betts',
    cardSize: 'SMALL',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'WHITE',
  },
  {
    entityId: 'ITEM-0024',
    recordId: 'rec-0024',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Grinding Wheel 6" x 1" x 1"',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'CONSUMABLE', subType: 'ABRASIVE' },
    useCase: 'Bench grinding',
    locator: { facility: 'Main Warehouse', department: 'Tool Crib', location: 'Cabinet TC-7' },
    internalSKU: 'TC-GW-6X1X1',
    generalLedgerCode: 'GL-7400',
    minQuantity: { amount: 5, unit: 'EACH' },
    notes: 'Aluminum oxide, 60 grit, medium grade',
    cardNotesDefault: 'Inspect for cracks before use',
    taxable: true,
    primarySupply: {
      supplier: 'Norton Abrasives',
      name: '6" Bench Grinding Wheel',
      sku: 'NOR-6X1X1-60',
      orderMechanism: 'ONLINE',
      url: 'https://www.nortonabrasives.com/grinding-wheels',
      orderQuantity: { amount: 10, unit: 'EACH' },
      unitCost: { value: 15.5, currency: 'USD' },
      orderCost: { value: 155.0, currency: 'USD' },
    },
    defaultSupply: 'Norton Abrasives',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'GRAY',
  },
  {
    entityId: 'ITEM-0025',
    recordId: 'rec-0025',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Thermal Transfer Ribbon 4.33" x 1476ft',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'CONSUMABLE', subType: 'PRINTING' },
    useCase: 'Label printing',
    locator: { facility: 'Main Warehouse', department: 'Shipping', location: 'Cabinet SH-2' },
    internalSKU: 'SH-RIBBON-433',
    generalLedgerCode: 'GL-7500',
    minQuantity: { amount: 5, unit: 'ROLL' },
    notes: 'Wax/resin blend, compatible with Zebra printers',
    cardNotesDefault: 'Store away from heat and sunlight',
    taxable: true,
    primarySupply: {
      supplier: 'Zebra Technologies',
      name: '4.33" TTR Ribbon',
      sku: 'ZEB-TTR-433-1476',
      orderMechanism: 'ONLINE',
      url: 'https://www.zebra.com/printer-supplies',
      orderQuantity: { amount: 12, unit: 'ROLL' },
      unitCost: { value: 22.5, currency: 'USD' },
      orderCost: { value: 270.0, currency: 'USD' },
    },
    defaultSupply: 'Zebra Technologies',
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'SMALL',
    color: 'BLACK',
  },
];

export const mockDraftItems: Item[] = [
  {
    entityId: 'ITEM-9001',
    recordId: 'rec-9001',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Adjustable Wrench 12" - Need to verify...',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'TOOL', subType: 'HAND_TOOL' },
    useCase: 'General maintenance',
    locator: { facility: 'Main Warehouse', department: 'Tool Crib' },
    internalSKU: 'TC-WRENCH-12',
    generalLedgerCode: 'GL-8000',
    minQuantity: { amount: 10, unit: 'EACH' },
    notes: 'Draft - need supplier quotes',
    cardNotesDefault: 'TBD',
    taxable: true,
    primarySupply: {
      supplier: 'TBD',
      name: 'Adjustable Wrench 12"',
      orderMechanism: 'ONLINE',
      orderQuantity: { amount: 20, unit: 'EACH' },
      unitCost: { value: 0.0, currency: 'USD' },
      orderCost: { value: 0.0, currency: 'USD' },
    },
    defaultSupply: 'TBD',
    cardSize: 'MEDIUM',
    labelSize: 'SMALL',
    breadcrumbSize: 'SMALL',
    color: 'GRAY',
  },
  {
    entityId: 'ITEM-9002',
    recordId: 'rec-9002',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'LED Work Light 50W - Incomplete specs',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'LIGHTING' },
    useCase: 'Work area illumination',
    locator: { facility: 'Main Warehouse' },
    internalSKU: 'EL-LIGHT-LED50',
    notes: 'Draft - pending electrical spec review',
    taxable: true,
    primarySupply: {
      supplier: 'TBD',
      orderMechanism: 'ONLINE',
      orderQuantity: { amount: 10, unit: 'EACH' },
      unitCost: { value: 0.0, currency: 'USD' },
      orderCost: { value: 0.0, currency: 'USD' },
    },
    cardSize: 'MEDIUM',
    labelSize: 'MEDIUM',
    breadcrumbSize: 'MEDIUM',
    color: 'YELLOW',
  },
  {
    entityId: 'ITEM-9003',
    recordId: 'rec-9003',
    author: 'system',
    timeCoordinates: timeCoordinates(),
    createdCoordinates: timeCoordinates(),
    name: 'Forklift Battery Charger - Need approval',
    imageUrl:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='150'%3E%3Crect width='150' height='150' fill='%23e5e7eb'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' fill='%239ca3af' font-family='sans-serif' font-size='14'%3ENo Image%3C/text%3E%3C/svg%3E",
    classification: { type: 'EQUIPMENT', subType: 'CHARGER' },
    useCase: 'Forklift maintenance',
    locator: { facility: 'Main Warehouse', department: 'Maintenance' },
    internalSKU: 'MT-CHARGER-FL24',
    generalLedgerCode: 'GL-8100',
    notes: 'Draft - awaiting budget approval',
    cardNotesDefault: 'High voltage - certified personnel only',
    taxable: true,
    primarySupply: {
      supplier: 'Crown Equipment',
      name: '24V Forklift Charger',
      sku: 'CRW-CHG-24V',
      orderMechanism: 'PURCHASE_ORDER',
      url: 'https://www.crown.com/battery-chargers',
      orderQuantity: { amount: 1, unit: 'EACH' },
      unitCost: { value: 3500.0, currency: 'USD' },
      orderCost: { value: 3500.0, currency: 'USD' },
    },
    defaultSupply: 'Crown Equipment',
    cardSize: 'X_LARGE',
    labelSize: 'LARGE',
    breadcrumbSize: 'LARGE',
    color: 'RED',
  },
];
