import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WireframeModeProvider } from "@/components/wireframe-mode-provider";
import { SiteHeader } from "@/components/site-header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arda UX Prototypes",
  description:
    "Wireframe prototype gallery for Arda frontend components. Generated by AI agents, reviewed by humans.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WireframeModeProvider>
          <div className="flex min-h-screen flex-col">
            <SiteHeader />
            <main className="flex-1">{children}</main>
          </div>
        </WireframeModeProvider>
      </body>
    </html>
  );
}
