import type { BusinessAffiliate } from '@/types/reference/business-affiliates/business-affiliate';

export const mockSuppliers: BusinessAffiliate[] = [
  {
    eId: 'ba-001',
    name: 'Fastenal Corp.',
    legal: {
      name: 'Fastenal Corp.',
      legalName: 'Fastenal Company',
      country: 'US',
      taxId: '41-0948415',
    },
    roles: [{ role: 'VENDOR', notes: 'Primary MRO supplier' }, { role: 'CUSTOMER' }],
    contact: {
      firstName: 'Sarah',
      lastName: 'Chen',
      email: 'sarah.chen@fastenal.com',
      phone: '+1-507-454-5374',
    },
    mainAddress: {
      addressLine1: '2001 Theurer Blvd',
      city: 'Winona',
      state: 'MN',
      postalCode: '55987',
      country: 'US',
    },
    notes: 'Preferred vendor for fasteners and MRO supplies.',
  },
  {
    eId: 'ba-002',
    name: 'Parker Hannifin',
    legal: {
      name: 'Parker Hannifin',
      legalName: 'Parker-Hannifin Corporation',
      country: 'US',
      taxId: '34-0451060',
    },
    roles: [{ role: 'VENDOR', notes: 'Hydraulic components' }, { role: 'OTHER' }],
    contact: {
      firstName: 'James',
      lastName: 'Rodriguez',
      email: 'j.rodriguez@parker.com',
      phone: '+1-216-896-3000',
    },
    mainAddress: {
      addressLine1: '6035 Parkland Blvd',
      city: 'Cleveland',
      state: 'OH',
      postalCode: '44124',
      country: 'US',
    },
  },
  {
    eId: 'ba-003',
    name: 'Grainger Industrial',
    legal: {
      name: 'Grainger Industrial',
      legalName: 'W.W. Grainger, Inc.',
      country: 'US',
      taxId: '36-1150280',
    },
    roles: [{ role: 'VENDOR' }, { role: 'CUSTOMER' }],
    contact: {
      firstName: 'Maria',
      lastName: 'Gonzalez',
      email: 'm.gonzalez@grainger.com',
      phone: '+1-847-535-1000',
    },
    mainAddress: {
      addressLine1: '100 Grainger Parkway',
      city: 'Lake Forest',
      state: 'IL',
      postalCode: '60045',
      country: 'US',
    },
    notes: 'Large-volume distributor with next-day delivery.',
  },
  {
    eId: 'ba-004',
    name: 'SKF Distribution',
    legal: {
      name: 'SKF Distribution',
      legalName: 'SKF USA Inc.',
      country: 'US',
      taxId: '56-1234567',
    },
    roles: [{ role: 'VENDOR' }],
    contact: {
      firstName: 'Erik',
      lastName: 'Lindqvist',
      email: 'e.lindqvist@skf.com',
      phone: '+1-267-436-6000',
    },
    mainAddress: {
      addressLine1: '890 Forty Foot Rd',
      city: 'Lansdale',
      state: 'PA',
      postalCode: '19446',
      country: 'US',
    },
    notes: 'Bearings and seals specialist.',
  },
  {
    eId: 'ba-005',
    name: 'Gates Industrial',
    legal: {
      name: 'Gates Industrial',
      legalName: 'Gates Corporation',
      country: 'US',
      taxId: '84-2345678',
    },
    roles: [{ role: 'VENDOR' }, { role: 'OTHER' }],
    contact: {
      firstName: 'Thomas',
      lastName: 'Burke',
      email: 't.burke@gates.com',
      phone: '+1-303-744-1911',
    },
    mainAddress: {
      addressLine1: '1144 Fifteenth St',
      city: 'Denver',
      state: 'CO',
      postalCode: '80202',
      country: 'US',
    },
  },
  {
    eId: 'ba-006',
    name: 'SafetyFirst Inc.',
    legal: {
      name: 'SafetyFirst Inc.',
      legalName: 'SafetyFirst International LLC',
      country: 'US',
      taxId: '22-3456789',
    },
    roles: [{ role: 'VENDOR' }],
    contact: {
      firstName: 'Linda',
      lastName: 'Park',
      email: 'l.park@safetyfirst.com',
      phone: '+1-800-555-0199',
    },
    mainAddress: {
      addressLine1: '500 Industrial Dr',
      city: 'Atlanta',
      state: 'GA',
      postalCode: '30301',
      country: 'US',
    },
    notes: 'PPE and safety equipment provider.',
  },
  {
    eId: 'ba-007',
    name: 'HydroTech Systems',
    legal: {
      name: 'HydroTech Systems',
      legalName: 'HydroTech Systems Corp.',
      country: 'US',
      taxId: '33-4567890',
    },
    roles: [{ role: 'VENDOR' }, { role: 'OPERATOR' }],
    contact: {
      firstName: 'David',
      lastName: 'Kim',
      email: 'd.kim@hydrotech.com',
      phone: '+1-713-555-0187',
    },
    mainAddress: {
      addressLine1: '2200 Westheimer Rd',
      city: 'Houston',
      state: 'TX',
      postalCode: '77098',
      country: 'US',
    },
  },
  {
    eId: 'ba-008',
    name: 'Shell Lubricants',
    legal: {
      name: 'Shell Lubricants',
      legalName: 'Shell Oil Company',
      country: 'US',
      taxId: '73-5678901',
    },
    roles: [{ role: 'VENDOR' }],
    contact: {
      firstName: 'Rachel',
      lastName: 'Webb',
      email: 'r.webb@shell.com',
      phone: '+1-713-241-6161',
    },
    mainAddress: {
      addressLine1: '150 North Dairy Ashford Rd',
      city: 'Houston',
      state: 'TX',
      postalCode: '77079',
      country: 'US',
    },
    notes: 'Industrial lubricants and greases.',
  },
  {
    eId: 'ba-009',
    name: 'Siemens Energy',
    legal: { name: 'Siemens Energy', legalName: 'Siemens Energy AG', country: 'DE' },
    roles: [{ role: 'VENDOR' }, { role: 'CARRIER' }],
    contact: {
      firstName: 'Hans',
      lastName: 'Mueller',
      email: 'h.mueller@siemens-energy.com',
      phone: '+49-89-636-00',
    },
    mainAddress: {
      addressLine1: 'Otto-Hahn-Ring 6',
      city: 'Munich',
      state: 'BY',
      postalCode: '81739',
      country: 'DE',
    },
  },
  {
    eId: 'ba-010',
    name: 'Acme Logistics',
    legal: {
      name: 'Acme Logistics',
      legalName: 'Acme Logistics Inc.',
      country: 'US',
      taxId: '44-6789012',
    },
    roles: [{ role: 'CARRIER' }],
    contact: {
      firstName: 'Kevin',
      lastName: 'Tran',
      email: 'k.tran@acmelogistics.com',
      phone: '+1-555-0142',
    },
    mainAddress: {
      addressLine1: '800 Logistics Way',
      city: 'Memphis',
      state: 'TN',
      postalCode: '38118',
      country: 'US',
    },
    notes: 'Regional freight carrier, next-day Midwest.',
  },
  {
    eId: 'ba-011',
    name: 'Precision Machining Co.',
    legal: {
      name: 'Precision Machining Co.',
      legalName: 'Precision Machining Company LLC',
      country: 'US',
      taxId: '55-7890123',
    },
    roles: [{ role: 'VENDOR' }, { role: 'OPERATOR' }],
    contact: {
      firstName: 'Angela',
      lastName: 'Rossi',
      email: 'a.rossi@precisionmachining.com',
      phone: '+1-313-555-0175',
    },
    mainAddress: {
      addressLine1: '1500 Manufacturing Blvd',
      city: 'Detroit',
      state: 'MI',
      postalCode: '48201',
      country: 'US',
    },
  },
  {
    eId: 'ba-012',
    name: 'FedEx Freight',
    legal: {
      name: 'FedEx Freight',
      legalName: 'FedEx Freight Inc.',
      country: 'US',
      taxId: '62-8901234',
    },
    roles: [{ role: 'CARRIER' }],
    contact: {
      firstName: 'Tammy',
      lastName: 'Johnson',
      email: 't.johnson@fedex.com',
      phone: '+1-800-463-3339',
    },
    mainAddress: {
      addressLine1: '942 South Shady Grove Rd',
      city: 'Memphis',
      state: 'TN',
      postalCode: '38120',
      country: 'US',
    },
  },
  {
    eId: 'ba-013',
    name: 'Midwest Manufacturing',
    legal: { name: 'Midwest Manufacturing', country: 'US', taxId: '37-9012345' },
    roles: [{ role: 'CUSTOMER' }],
    contact: {
      firstName: 'Robert',
      lastName: 'Smith',
      email: 'r.smith@midwestmfg.com',
      phone: '+1-614-555-0163',
    },
    mainAddress: {
      addressLine1: '300 Factory Lane',
      city: 'Columbus',
      state: 'OH',
      postalCode: '43215',
      country: 'US',
    },
    notes: 'Key customer for card printing services.',
  },
  {
    eId: 'ba-014',
    name: 'Toyota Tsusho',
    legal: { name: 'Toyota Tsusho', legalName: 'Toyota Tsusho America Inc.', country: 'JP' },
    roles: [{ role: 'VENDOR' }, { role: 'CUSTOMER' }],
    contact: {
      firstName: 'Yuki',
      lastName: 'Tanaka',
      email: 'y.tanaka@toyota-tsusho.com',
      phone: '+81-52-584-5000',
    },
    mainAddress: {
      addressLine1: '9-8 Meieki 4-chome',
      city: 'Nagoya',
      state: 'Aichi',
      country: 'JP',
    },
  },
  {
    eId: 'ba-015',
    name: 'General Parts Supply',
    legal: {
      name: 'General Parts Supply',
      legalName: 'General Parts Supply LLC',
      country: 'US',
      taxId: '48-0123456',
    },
    roles: [{ role: 'VENDOR' }],
    contact: {
      firstName: 'Patricia',
      lastName: 'Davis',
      email: 'p.davis@generalparts.com',
      phone: '+1-800-555-0188',
    },
    mainAddress: {
      addressLine1: '4200 Commerce Pkwy',
      city: 'Charlotte',
      state: 'NC',
      postalCode: '28208',
      country: 'US',
    },
    notes: 'General industrial parts and supplies.',
  },
];
