import type { Preview } from '@storybook/react-vite';
import { withAgentation } from './addons/agentation-toggle/with-agentation';
import { withFullAppProviders } from '../src/decorators/with-full-app-providers';
import { initialize, mswLoader } from 'msw-storybook-addon';
import { handlers } from '@frontend/mocks/handlers';

import '../src/styles/globals.css';
import '../src/styles/ag-theme-arda.css';

initialize({
  onUnhandledRequest: 'bypass',
  serviceWorker: { url: './mockServiceWorker.js' },
});

const preview: Preview = {
  decorators: [withAgentation, withFullAppProviders],
  loaders: [mswLoader],
  initialGlobals: {
    agentationEnabled: false,
  },
  parameters: {
    msw: { handlers },
    options: {
      storySort: {
        order: [
          'Docs',
          [
            'About',
            'Arda Style Guide',
            'Getting Started',
            'Storybook Structure',
            ['Dev Witness', ['Contributing', 'Integration'], 'Use Cases'],
            'Workflows',
            [
              'Developer Workflow',
              'Creating Stories',
              'Canary Components',
              ['How to Extract and Publish', 'Example'],
              'Publishing',
            ],
            'Components',
            ['Classification', 'Guidelines', 'Usage Patterns', ['Creating Entity Viewers']],
            'Tools',
            ['Agentation'],
            'Misc',
            ['From Figma', 'Applications'],
          ],
          'Components',
          [
            'Atoms',
            ['Guide', 'General', 'Display and Layout', 'Grid', 'Form', 'Other'],
            'Molecules',
            ['Guide', '*'],
            'Organisms',
            ['Guide', 'Shared', 'Reference', '*'],
            'Canary',
            [
              'Utilities',
              'Atoms',
              [
                'Guide',
                'Avatar',
                ['Docs', '*', 'Playground'],
                'Badge',
                ['Docs', '*', 'Playground'],
                'BrandLogo',
                'Button',
                'Card',
                'CopyrightAcknowledgment',
                ['Docs', '*', 'Playground'],
                'Dialog',
                'Drawer',
                'IconButton',
                'IconLabel',
                'InputGroup',
                'ReadOnlyField',
                'SearchInput',
                'Grid',
                [
                  'Guide',
                  'Boolean',
                  ['Docs', '*', 'Playground'],
                  'Color',
                  ['Docs', '*', 'Playground'],
                  'Date',
                  ['Docs', '*', 'Playground'],
                  'Image',
                  ['Docs', '*', 'Playground'],
                  'Memo',
                  ['Docs', '*', 'Playground'],
                  'Number',
                  ['Docs', '*', 'Playground'],
                  'Select',
                  ['Docs', '*', 'Playground'],
                  'Text',
                  ['Docs', '*', 'Playground'],
                  '*',
                ],
                '*',
              ],
              'Molecules',
              [
                'Guide',
                'ActionToolbar',
                'DataGrid',
                'FieldList',
                'Form',
                ['Guide', 'ImageFormField', ['Docs', '*', 'Playground'], '*'],
                'GridAction',
                'ImageComparisonLayout',
                ['Docs', '*', 'Playground'],
                'ImageDisplay',
                ['Docs', '*', 'Playground'],
                'ImageDropZone',
                ['Docs', '*', 'Playground'],
                'ImageHoverPreview',
                ['Docs', '*', 'Playground'],
                'ImageInspectorOverlay',
                ['Docs', '*', 'Playground'],
                'ImagePreviewEditor',
                ['Docs', '*', 'Playground'],
                'ItemDetails',
                ['Guide', '*'],
                'ItemGrid',
                ['Guide', '*'],
                'OverflowToolbar',
                'Sidebar',
                ['Guide', '*'],
                '*',
              ],
              'Organisms',
              [
                'Guide',
                'AppHeader',
                'ItemDetails',
                'ItemGrid',
                'Sidebar',
                'Shared',
                [
                  'Guide',
                  'Entity Data Grid',
                  ['Docs', 'Playground', '*'],
                  'Entity Data Grid Shim',
                  'ImageUploadDialog',
                  ['Docs', '*', 'Playground'],
                  '*',
                ],
                '*',
              ],
              'Primitives',
              [
                'Docs',
                'AlertDialog (Image Context)',
                'ImportCheck',
                'Skeleton (Image Context)',
                'Tabs (Image Context)',
                '*',
              ],
            ],
            'Extras',
            ['Atoms', 'Molecules', 'Organisms', '*'],
            '*',
          ],
          'Visual Elements',
          [
            'Brand Assets',
            'Colors',
            'Icons',
            'Vendored',
            ['Brand Assets', 'Colors', 'Icons'],
            'Canary',
            ['Brand Assets', 'Colors', 'Icons'],
          ],
          'Dev Witness',
          'Canary Refactor',
          'Use Cases',
          [
            'General Behaviors',
            ['Description', 'List Views', ['Description', '*'], '*'],
            'Reference',
            [
              'Business Affiliates',
              ['Description', '*', 'Ignore'],
              'Items',
              ['Description', '*'],
              '*',
            ],
            'Procurement',
            ['Context', 'References', 'Orders', 'Receiving', '*'],
            'Samples',
            '*',
          ],
          'Archive',
          ['About', 'Applications', '*'],
          '*',
        ],
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
