#!/usr/bin/env bash
# sync-frontend-app.sh — Sync vendored code from arda-frontend-app into ux-prototype
#
# Usage:
#   bash tools/sync-frontend-app.sh <SOURCE_REPO> [TARGET_DIR]
#
# Arguments:
#   SOURCE_REPO  Path to the arda-frontend-app repo root
#   TARGET_DIR   Destination directory (default: src/vendored/arda-frontend)
#
# This script is idempotent: it deletes TARGET_DIR before copying.

set -euo pipefail

SOURCE_REPO="${1:?Usage: sync-frontend-app.sh <SOURCE_REPO> [TARGET_DIR]}"
TARGET_DIR="${2:-src/vendored/arda-frontend}"

# Resolve paths
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET_DIR_ABS="$REPO_ROOT/$TARGET_DIR"

if [ ! -d "$SOURCE_REPO/src" ]; then
  echo "ERROR: $SOURCE_REPO/src does not exist" >&2
  exit 1
fi

# --- Step 1: Clean slate ---
if [ -d "$TARGET_DIR_ABS" ]; then
  echo "Removing existing $TARGET_DIR ..."
  rm -rf "$TARGET_DIR_ABS"
fi
mkdir -p "$TARGET_DIR_ABS"

# --- Step 2: Copy with blocklist ---
echo "Copying from $SOURCE_REPO/src/ to $TARGET_DIR ..."

# Use rsync with exclude patterns for the blocklist
rsync -a \
  --exclude='app/api/' \
  --exclude='app/layout.tsx' \
  --exclude='lib/jwt.ts' \
  --exclude='test-utils/' \
  --exclude='mocks/server.ts' \
  --exclude='lambda/' \
  --exclude='tests/' \
  --exclude='proxy.ts' \
  --exclude='lib/api-helpers.ts' \
  --exclude='components/PylonChatWidget.tsx' \
  "$SOURCE_REPO/src/" "$TARGET_DIR_ABS/"

echo "Copy complete."

# --- Step 3: Verify no blocklisted files leaked through ---
LEAKED=0
for pattern in \
  "$TARGET_DIR_ABS/app/api" \
  "$TARGET_DIR_ABS/app/layout.tsx" \
  "$TARGET_DIR_ABS/lib/jwt.ts" \
  "$TARGET_DIR_ABS/test-utils" \
  "$TARGET_DIR_ABS/mocks/server.ts" \
  "$TARGET_DIR_ABS/lambda" \
  "$TARGET_DIR_ABS/tests" \
  "$TARGET_DIR_ABS/proxy.ts" \
  "$TARGET_DIR_ABS/lib/api-helpers.ts" \
  "$TARGET_DIR_ABS/components/PylonChatWidget.tsx"; do
  if [ -e "$pattern" ]; then
    echo "WARNING: Blocklisted item leaked through: $pattern" >&2
    LEAKED=1
  fi
done
if [ "$LEAKED" -eq 1 ]; then
  echo "ERROR: Blocklisted files found in output. Check exclude patterns." >&2
  exit 1
fi

# --- Step 4: Rewrite imports ---
echo "Rewriting imports: @/ -> @frontend/ ..."

# Find all .ts and .tsx files and rewrite imports
find "$TARGET_DIR_ABS" -type f \( -name '*.ts' -o -name '*.tsx' \) -print0 | \
  xargs -0 sed -i '' \
    -e "s|from '@/|from '@frontend/|g" \
    -e "s|from \"@/|from \"@frontend/|g"

echo "Import rewriting complete."

# --- Step 5: Generate vendored-deps.json ---
echo "Generating vendored-deps.json ..."

SOURCE_PKG="$SOURCE_REPO/package.json"
UX_PKG="$REPO_ROOT/package.json"
OUTPUT_FILE="$REPO_ROOT/vendored-deps.json"

if [ ! -f "$SOURCE_PKG" ]; then
  echo "ERROR: $SOURCE_PKG not found" >&2
  exit 1
fi

# Get source commit SHA
SOURCE_SHA="unknown"
if [ -d "$SOURCE_REPO/.git" ] || [ -f "$SOURCE_REPO/.git" ]; then
  SOURCE_SHA=$(cd "$SOURCE_REPO" && git rev-parse HEAD 2>/dev/null || echo "unknown")
fi

SYNCED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Use node to extract and filter dependencies
node -e "
const fs = require('fs');
const sourcePkg = JSON.parse(fs.readFileSync('$SOURCE_PKG', 'utf8'));
const uxPkg = JSON.parse(fs.readFileSync('$UX_PKG', 'utf8'));

// Skip list — packages that should NOT be installed
const skipList = new Set([
  'next',
  'crypto',
  'eslint-config-next',
]);
const skipPrefixes = ['@aws-sdk/'];

// Gather all ux-prototype dependencies (deps + devDeps + peerDeps)
const uxAllDeps = {
  ...uxPkg.dependencies,
  ...uxPkg.devDependencies,
  ...uxPkg.peerDependencies,
};

// Process source dependencies (both deps and devDeps)
const allSourceDeps = {
  ...sourcePkg.dependencies,
  ...sourcePkg.devDependencies,
};

const vendoredDeps = {};
const conflicts = [];

for (const [name, version] of Object.entries(allSourceDeps)) {
  // Check skip list
  if (skipList.has(name)) continue;
  if (skipPrefixes.some(p => name.startsWith(p))) continue;
  // Check if name matches skip pattern 'aws-jwt-verify'
  if (name === 'aws-jwt-verify') continue;

  // Check if already in ux-prototype
  if (uxAllDeps[name]) {
    // Check for version conflicts
    const uxVer = uxAllDeps[name];
    if (uxVer !== version) {
      conflicts.push({ name, source: version, uxPrototype: uxVer });
    }
    continue; // Already present, skip
  }

  vendoredDeps[name] = version;
}

// Report conflicts
if (conflicts.length > 0) {
  console.error('Version conflicts detected:');
  for (const c of conflicts) {
    console.error('  ' + c.name + ': source=' + c.source + ' ux-prototype=' + c.uxPrototype);
  }
}

const output = {
  _source_sha: '$SOURCE_SHA',
  _synced_at: '$SYNCED_AT',
  _description: 'Dependencies from arda-frontend-app needed by vendored code. Auto-generated by tools/sync-frontend-app.sh.',
  dependencies: vendoredDeps,
};

fs.writeFileSync('$OUTPUT_FILE', JSON.stringify(output, null, 2) + '\n');
console.log('Wrote ' + Object.keys(vendoredDeps).length + ' vendored dependencies to vendored-deps.json');
"

echo "Done. Vendored code synced to $TARGET_DIR"
